=== Smeilz/acpc_poker_server/xsd/config.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified"
            xmlns="urn:nonstandard:config" 
            targetNamespace="urn:nonstandard:config">

  <xsd:element name="Config" type="Config"/>

  <xsd:complexType name="Config">
    <xsd:sequence>
      <xsd:element name="Room" type="Room" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="BotList" type="BotList" minOccurs="0" maxOccurs="1"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="Room">
    <xsd:all>
      <xsd:element name="Name" type="xsd:string" minOccurs="1"/>
      <xsd:element name="Gamedef" type="xsd:string" minOccurs="1"/>
      <xsd:element name="Port" type="xsd:positiveInteger" minOccurs="1"/>
    </xsd:all>
  </xsd:complexType>
  
  <xsd:complexType name="BotList">
    <xsd:sequence>
      <xsd:element name="Bot" type="Bot" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="Bot">
    <xsd:all>
      <xsd:element name="Type" type="xsd:string" minOccurs="1"/>
      <xsd:element name="Name" type="xsd:string" minOccurs="1"/>
      <xsd:element name="BuyIn" type="xsd:positiveInteger" minOccurs="1"/>
      <xsd:element name="Seat" type="xsd:nonNegativeInteger" minOccurs="1"/>
      <xsd:element name="Args" type="xsd:string" minOccurs="0"/>
    </xsd:all>
  </xsd:complexType>

</xsd:schema>

=== Smeilz/acpc_poker_server/config/psyctest.weak.limit.config.xml
<?xml version="1.0" encoding="UTF-8"?>
<Config xmlns="urn:nonstandard:config"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="urn:nonstandard:config 
     file:xsd/config.xsd">

 <Room>
  <Name>Psyccology Experiment</Name>
  <Gamedef>gamedef/psyc.2Player.limit.gamedef.xml</Gamedef>
  <Port>1001</Port>        
 </Room>

 <BotList>
  <Bot>
   <Type>AAAIPlayer</Type>
   <Name>Polaris</Name>
   <BuyIn>200</BuyIn>
   <Seat>0</Seat>
   <Args>scripts/psyctest.weak.limit.sh</Args>
  </Bot>

 </BotList>
</Config>

=== Smeilz/acpc_poker_server/config/headsup.nolimit.config.xml
<?xml version="1.0" encoding="UTF-8"?>
<Config xmlns="urn:nonstandard:config"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="urn:nonstandard:config 
     file:xsd/config.xsd">

 <Room>
  <Name>Headsup No Limit</Name>
  <Gamedef>gamedef/2Player.nolimit.gamedef.xml</Gamedef>
  <Port>1001</Port>        
 </Room>

 <BotList>
  <Bot>
   <Type>AAAIPlayer</Type>
   <Name>Polaris</Name>
   <BuyIn>400</BuyIn>
   <Seat>0</Seat>
   <Args>scripts/headsup.nolimit.sh</Args>
  </Bot>

 </BotList>
</Config>

=== Smeilz/acpc_poker_server/config/man_vs_machine.config.xml
<?xml version="1.0" encoding="UTF-8"?>
<Config xmlns="urn:nonstandard:config"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="urn:nonstandard:config 
     file:xsd/config.xsd">

 <Room>
  <Name>Man vs Machine</Name>
  <Gamedef>gamedef/2Player.limit.gamedef.xml</Gamedef>
  <Port>9001</Port>        
 </Room>

 <BotList>
  <Bot>
   <Type>AAAIPlayer</Type>
   <Name>Polaris</Name>
   <BuyIn>200</BuyIn>
   <Seat>0</Seat>
   <Args>scripts/man_vs_machine.sh</Args>
  </Bot>

 </BotList>
</Config>

=== Smeilz/acpc_poker_server/config/CONFIG.SAMPLE.xml
<?xml version="1.0" encoding="UTF-8"?>
<Config xmlns="urn:nonstandard:config"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="urn:nonstandard:config 
     file:xsd/config.xsd">

 <Room>
  <Name>SampleRoom</Name>
  <Gamedef>gamedef/2Player.limit.gamedef.xml</Gamedef>
  <Port>9001</Port>        
 </Room>

 <BotList>
  <Bot>
   <Type>AAAIPlayer</Type>
   <Name>SamplerPlayer1</Name>
   <BuyIn>20</BuyIn>
   <Seat>0</Seat>
   <Args>scripts/Player1.testscript.sh</Args>
  </Bot>
  <Bot>
   <Type>AAAIPlayer</Type>
   <Name>SamplerPlayer2</Name>
   <BuyIn>20</BuyIn>
   <Seat>1</Seat>
   <Args>scripts/Player2.testscript.sh</Args>
  </Bot>

 </BotList>
</Config>
